project:
  type: website
  output-dir: docs

website:
  title: "PhysicalGeographyGiessen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: luminescence.qmd
        text: Luminescence Dating
      - href: lab.qmd
        text: Giessen Luminescence Laborytory
      - href: database.qmd
        text: Luminescence Labs Worldwide
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



